"""Deterministic LLM stand-in used by every non-live test and by ``--dry-run``.

It reads the rendered prompt and returns schema-valid JSON, so the whole
pipeline can be exercised end to end without spending anything (spec section 47).

The content is intentionally generic placeholder text. It is labelled as mock
data in the research summary and the script title so a mock render can never be
mistaken for a real one.
"""

from __future__ import annotations

from typing import Any

from pydantic import BaseModel

from ...utils import distribute_durations, normalize_whitespace, visible_length
from ..base import LLMJsonResponse, LLMUsage
from ._promptio import field, float_field, int_field, json_block

MOCK_MARKER = "[MOCK]"

_CLAIM_TEMPLATES = [
    "이 장치의 내부는 입력, 이송, 판별, 저장의 네 구간으로 나뉜다.",
    "첫 단계에서는 센서가 대상의 존재와 위치를 감지한다.",
    "이송 구간에서는 롤러와 벨트가 대상을 일정한 간격으로 밀어낸다.",
    "판별 구간에서는 광학 센서가 표면 정보를 읽어 기준값과 비교한다.",
    "기준과 다른 대상은 별도의 경로로 자동 분리된다.",
    "제어부는 각 센서의 신호를 밀리초 단위로 대조한다.",
    "이상이 감지되면 장치는 동작을 멈추고 오류를 기록한다.",
    "정상으로 처리된 대상만 최종 저장부로 이동한다.",
    "전체 과정은 사람이 개입하지 않아도 정해진 순서로 진행된다.",
    "정기 점검에서는 센서 오염과 부품 마모를 함께 확인한다.",
    "설계 단계에서 각 구간의 처리 속도는 서로 맞춰져 있다.",
    "기록된 오류는 나중에 점검 담당자가 다시 확인한다.",
]

_REVEAL_TEXT = "겉으로는 단순해 보이지만, 안에서는 여러 단계가 순서대로 움직입니다."
_SURPRISE_TEXT = "가장 까다로운 구간은 오차를 걸러내는 이 단계입니다."
_CLOSING_TEXT = "다음에 이 장면을 볼 때, 안에서 이런 순서가 지나간다고 생각해 보세요."
_FILLER_TEXT = "여기까지가 겉에서 보이는 부분이고, 이제부터가 안쪽 이야기입니다."

_NEGATIVES = [
    "visible text",
    "logos",
    "brand names",
    "distorted human hands",
    "duplicated objects",
]


class MockLLMProvider:
    """Returns schema-valid JSON derived from the rendered prompt."""

    name = "mock"

    def __init__(self, model: str = "mock-llm-1") -> None:
        self.model = model

    async def generate_json(
        self,
        *,
        system_prompt: str,
        user_prompt: str,
        schema: type[BaseModel],
    ) -> LLMJsonResponse:
        builders = {
            "ResearchResult": self._research,
            "ScriptResult": self._script,
            "ScenePlan": self._scene_plan,
            "FactCheckReport": self._fact_check,
        }
        builder = builders.get(schema.__name__)
        if builder is None:
            raise NotImplementedError(f"MockLLMProvider cannot produce {schema.__name__}")
        data = builder(user_prompt)
        return LLMJsonResponse(
            data=data,
            model=self.model,
            usage=LLMUsage(
                input_tokens=(len(system_prompt) + len(user_prompt)) // 4,
                output_tokens=len(str(data)) // 4,
            ),
        )

    # -- builders --------------------------------------------------------

    def _research(self, prompt: str) -> dict[str, Any]:
        topic = field(prompt, "TOPIC", "unknown topic")
        target_claims = max(4, int_field(prompt, "TARGET_CLAIMS", 10))
        sources: list[dict[str, Any]] = json_block(prompt, "SOURCES_JSON", []) or []
        if not sources:
            sources = [
                {
                    "id": "S01",
                    "title": "mock source",
                    "url": "https://example.invalid/mock",
                    "publisher": "mock",
                }
            ]

        claims = []
        for index in range(min(target_claims, len(_CLAIM_TEMPLATES))):
            source = sources[index % len(sources)]
            confidence = "high" if index < 4 else ("medium" if index < 8 else "low")
            claims.append(
                {
                    "id": f"C{index + 1:02d}",
                    "statement": _CLAIM_TEMPLATES[index],
                    "confidence": confidence,
                    "source_ids": [source["id"]],
                    "visualizable": index % 3 != 2,
                    "notes": "generated by MockLLMProvider",
                }
            )

        return {
            "topic": topic,
            "summary": (
                f"{MOCK_MARKER} 모의 조사 결과입니다. 실제 취재 결과가 아닙니다. "
                f"'{topic}' 주제의 시스템은 입력, 이송, 판별, 저장의 순서로 동작합니다. "
                "각 구간은 센서와 제어부가 서로 신호를 주고받으며 연결됩니다. "
                "실제 제작 전에 openai provider로 다시 조사해야 합니다."
            ),
            "claims": claims,
            "sources": sources,
            "unresolved_questions": [
                "이 데이터는 MockLLMProvider가 만든 것이며 검증된 사실이 아닙니다.",
            ],
            "unsafe_or_uncertain_claims": [],
        }

    def _script(self, prompt: str) -> dict[str, Any]:
        topic = field(prompt, "TOPIC", "unknown topic")
        target_chars = int_field(prompt, "TARGET_CHARS", 360)
        min_chars = int_field(prompt, "MIN_CHARS", 279)
        max_chars = int_field(prompt, "MAX_CHARS", 434)
        target_duration = float_field(prompt, "TARGET_DURATION_SEC", 58.0)
        chars_per_sec = float_field(prompt, "CHARS_PER_SEC", 6.2)
        claims: list[dict[str, Any]] = json_block(prompt, "CLAIMS_JSON", []) or []

        hook = topic if topic.endswith(("?", "!", ".")) else f"{topic}?"
        beats: list[dict[str, Any]] = [
            {"id": "B01", "purpose": "hook", "text": hook, "claim_ids": []},
            {"id": "B02", "purpose": "reveal", "text": _REVEAL_TEXT, "claim_ids": []},
        ]
        tail = [
            {"purpose": "surprise", "text": _SURPRISE_TEXT, "claim_ids": []},
            {"purpose": "closing", "text": _CLOSING_TEXT, "claim_ids": []},
        ]

        def total_chars(process: list[dict[str, Any]]) -> int:
            texts = [b["text"] for b in beats + process + tail]
            return visible_length(" ".join(texts))

        process: list[dict[str, Any]] = []
        for claim in claims:
            if total_chars(process) >= target_chars:
                break
            process.append(
                {
                    "purpose": "process",
                    "text": claim["statement"],
                    "claim_ids": [claim["id"]],
                }
            )
        # Too short (few or no claims): pad with non-factual connective lines.
        while total_chars(process) < min_chars:
            process.append({"purpose": "process", "text": _FILLER_TEXT, "claim_ids": []})
        # Too long: drop process beats from the end, never below one.
        while total_chars(process) > max_chars and len(process) > 1:
            process.pop()

        ordered = beats + process + tail
        for index, beat in enumerate(ordered, start=1):
            beat["id"] = f"B{index:02d}"

        narration = " ".join(beat["text"] for beat in ordered)
        estimated = round(visible_length(narration) / chars_per_sec, 2)
        duration = min(max(estimated, 45.0), 70.0) if estimated else target_duration

        referenced = [cid for beat in ordered for cid in beat["claim_ids"]]
        return {
            "title": f"{MOCK_MARKER} {topic}",
            "hook": hook,
            "narration": narration,
            "beats": ordered,
            "target_duration_sec": duration,
            "referenced_claim_ids": referenced,
            "estimated_word_count": len(narration.split()),
        }

    def _scene_plan(self, prompt: str) -> dict[str, Any]:
        topic = field(prompt, "TOPIC", "unknown topic")
        default_reality = field(prompt, "DEFAULT_REALITY_TYPE", "reconstructed")
        min_scenes = int_field(prompt, "MIN_SCENES", 8)
        max_scenes = int_field(prompt, "MAX_SCENES", 14)
        target_duration = float_field(prompt, "TARGET_DURATION_SEC", 58.0)
        min_scene = float_field(prompt, "MIN_SCENE_DURATION_SEC", 1.5)
        max_scene = float_field(prompt, "MAX_SCENE_DURATION_SEC", 9.0)
        max_high = int_field(prompt, "MAX_HIGH_PRIORITY_SCENES", 4)

        pattern: list[str] = json_block(prompt, "REVEAL_PATTERN_JSON", []) or ["overview"]
        cameras: list[str] = json_block(prompt, "PREFERRED_CAMERA_JSON", []) or ["slow dolly in"]
        visuals: list[str] = json_block(prompt, "PREFERRED_VISUALS_JSON", []) or ["cutaway"]
        script: dict[str, Any] = json_block(prompt, "SCRIPT_JSON", {}) or {}

        units = _units_from_script(script, min_scenes, max_scenes)
        weights = [max(visible_length(unit["text"]), 1) for unit in units]
        durations = distribute_durations(
            [float(w) for w in weights],
            target_duration,
            min_each=min_scene,
            max_each=max_scene,
        )

        continuity = [
            {
                "continuity_id": "MAIN_SUBJECT",
                "fixed_description": (
                    f"the main subject of '{topic}', matte grey housing, "
                    "rounded corners, one small amber status light"
                ),
            }
        ]

        high_used = 0
        scenes: list[dict[str, Any]] = []
        for index, (unit, duration) in enumerate(zip(units, durations, strict=True)):
            purpose = unit["purpose"]
            is_hook = index == 0
            is_surprise = purpose == "surprise"
            priority = "medium"
            if (is_hook or is_surprise) and high_used < max_high:
                priority = "high"
                high_used += 1
            elif not unit["claim_ids"] and not is_hook and purpose != "closing":
                priority = "low"

            stage_name = pattern[index % len(pattern)]
            scenes.append(
                {
                    "id": f"S{index + 1:02d}",
                    "order": index + 1,
                    "narration": unit["text"],
                    "duration_sec": duration,
                    "purpose": f"{purpose} / {stage_name}",
                    "visual_subject": f"{topic} — {stage_name.replace('_', ' ')}",
                    "environment": f"{stage_name.replace('_', ' ')} setting around the subject",
                    "action": (
                        f"{visuals[index % len(visuals)].replace('_', ' ')} revealing the "
                        f"{stage_name.replace('_', ' ')} stage"
                    ),
                    "camera": cameras[index % len(cameras)].replace("_", " "),
                    "framing": "vertical 9:16, subject centred in the safe area",
                    "lighting": "soft directional key light with practical accents",
                    "reality_type": "observed" if is_hook else default_reality,
                    "priority": priority,
                    "asset_type": "image_motion" if priority == "low" else "video",
                    "continuity": continuity if index < 2 or index == len(units) - 1 else [],
                    "claim_ids": unit["claim_ids"],
                    "transition_in": "cut" if index == 0 else "match cut",
                    "transition_out": "cut",
                    "negative_constraints": list(_NEGATIVES),
                }
            )

        return {
            "scenes": scenes,
            "continuity": continuity,
            "visual_notes": f"{MOCK_MARKER} scene plan generated by MockLLMProvider",
        }

    def _fact_check(self, prompt: str) -> dict[str, Any]:
        return {
            "unsupported_sentences": [],
            "overreaching_sentences": [],
            "verdict": "pass",
            "notes": f"{MOCK_MARKER} no review performed",
        }


def _units_from_script(
    script: dict[str, Any], min_scenes: int, max_scenes: int
) -> list[dict[str, Any]]:
    """Turn script beats into scene-sized units within the scene-count window."""
    beats = script.get("beats") or []
    units = [
        {
            "text": normalize_whitespace(beat.get("text", "")),
            "purpose": beat.get("purpose", "process"),
            "claim_ids": list(beat.get("claim_ids", [])),
        }
        for beat in beats
        if normalize_whitespace(beat.get("text", ""))
    ]
    if not units:
        narration = normalize_whitespace(script.get("narration", "")) or "…"
        units = [{"text": narration, "purpose": "process", "claim_ids": []}]

    # Merge the shortest adjacent pair until the plan fits the maximum.
    while len(units) > max_scenes:
        lengths = [
            visible_length(units[i]["text"]) + visible_length(units[i + 1]["text"])
            for i in range(len(units) - 1)
        ]
        index = lengths.index(min(lengths))
        merged = {
            "text": f"{units[index]['text']} {units[index + 1]['text']}".strip(),
            "purpose": units[index]["purpose"],
            "claim_ids": units[index]["claim_ids"] + units[index + 1]["claim_ids"],
        }
        units[index : index + 2] = [merged]

    # Split the longest unit until the plan reaches the minimum.
    while len(units) < min_scenes:
        index = max(range(len(units)), key=lambda i: visible_length(units[i]["text"]))
        text = units[index]["text"]
        if len(text) < 8:
            break
        cut = _split_point(text)
        if cut is None:
            break
        head, tail = text[:cut].strip(), text[cut:].strip()
        units[index : index + 1] = [
            {**units[index], "text": head},
            {**units[index], "text": tail},
        ]
    return units


def _split_point(text: str) -> int | None:
    """Best place to cut a unit in two: nearest space to the middle."""
    middle = len(text) // 2
    spaces = [i for i, char in enumerate(text) if char == " "]
    if not spaces:
        return middle if len(text) >= 8 else None
    return min(spaces, key=lambda i: abs(i - middle))
