"""Deterministic LLM stand-in used by every non-live test and by ``--dry-run``.

It reads the rendered prompt and returns schema-valid JSON, so the whole
pipeline can be exercised end to end without spending anything.

The content comes from hand-written fixtures in :mod:`.scenarios`, written the
way a good research/writer/director pass should look. That matters: a mock that
returned vague filler would make the content-quality contract untestable, since
the contract's whole job is to reject vague filler.

Everything is still labelled `[MOCK]` in the title and the research summary, and
a run using this provider can never produce ``final.mp4``.
"""

from __future__ import annotations

from typing import Any

from pydantic import BaseModel

from ...utils import distribute_durations, normalize_whitespace, visible_length
from ..base import LLMJsonResponse, LLMUsage
from ._promptio import field, float_field, int_field, json_block
from .scenarios import Scenario, Step, scenario_for

MOCK_MARKER = "[MOCK]"

#: Mistakes a particular shot invites. Global bans live in the Style Bible.
_SCENE_NEGATIVES = ("duplicated objects", "impossible geometry", "melting edges")


class MockLLMProvider:
    """Returns schema-valid JSON derived from the rendered prompt."""

    name = "mock"
    is_mock = True

    def __init__(self, model: str = "mock-llm-1") -> None:
        self.model = model

    async def generate_json(
        self,
        *,
        system_prompt: str,
        user_prompt: str,
        schema: type[BaseModel],
    ) -> LLMJsonResponse:
        builders = {
            "ResearchResult": self._research,
            "ScriptResult": self._script,
            "ScenePlan": self._scene_plan,
            "FactCheckReport": self._fact_check,
        }
        builder = builders.get(schema.__name__)
        if builder is None:
            raise NotImplementedError(f"MockLLMProvider cannot produce {schema.__name__}")
        data = builder(user_prompt)
        return LLMJsonResponse(
            data=data,
            model=self.model,
            usage=LLMUsage(
                input_tokens=(len(system_prompt) + len(user_prompt)) // 4,
                output_tokens=len(str(data)) // 4,
            ),
        )

    # -- builders --------------------------------------------------------

    def _research(self, prompt: str) -> dict[str, Any]:
        topic = field(prompt, "TOPIC", "unknown topic")
        target_claims = max(4, int_field(prompt, "TARGET_CLAIMS", 10))
        scenario = scenario_for(topic, subject_of(topic))
        sources = _sources_from(prompt)

        steps = scenario.all_steps()[: max(target_claims, 6)]
        claims = [
            {
                "id": f"C{index + 1:02d}",
                "statement": step.statement,
                "confidence": "high" if index < 4 else ("medium" if index < 8 else "low"),
                "source_ids": [sources[index % len(sources)]["id"]],
                "visualizable": step.visualizable,
                "notes": "generated by MockLLMProvider",
            }
            for index, step in enumerate(steps)
        ]

        return {
            "topic": topic,
            "question": {
                "original_topic": topic,
                "resolved_question": scenario.resolved_question,
                "scope": scenario.scope,
                "excluded": list(scenario.excluded),
            },
            "summary": (
                f"{MOCK_MARKER} 모의 조사 결과입니다. 실제 취재 결과가 아닙니다. {scenario.summary}"
            ),
            "claims": claims,
            "sources": sources,
            "unresolved_questions": [
                "이 데이터는 MockLLMProvider가 만든 것이며 검증된 사실이 아닙니다.",
            ],
            "unsafe_or_uncertain_claims": [],
        }

    def _script(self, prompt: str) -> dict[str, Any]:
        topic = field(prompt, "TOPIC", "unknown topic")
        subject = subject_of(topic)
        scenario = scenario_for(topic, subject)
        hook_max_chars = int_field(prompt, "HOOK_MAX_CHARS", 18)
        hook = (
            scenario.hook
            if visible_length(scenario.hook) <= hook_max_chars
            else fit_hook(subject, hook_max_chars)
        )
        max_chars = int_field(prompt, "MAX_CHARS", 434)
        chars_per_sec = float_field(prompt, "CHARS_PER_SEC", 6.2)
        claims: list[dict[str, Any]] = json_block(prompt, "CLAIMS_JSON", []) or []
        # Research emitted one claim per step, in order, so index maps them back.
        steps = scenario.all_steps()
        claim_for = {
            id(step): claims[index]["id"] for index, step in enumerate(steps) if index < len(claims)
        }

        head = [
            _beat("hook", hook, None, None),
            # Required by the arc: without "here is the obvious answer and why
            # it fails", every step after it is an answer to nothing.
            _beat("problem", None, scenario.problem, claim_for.get(id(scenario.problem))),
        ]
        tail = [
            _beat("surprise", None, scenario.surprise, claim_for.get(id(scenario.surprise))),
            _beat("closing", None, scenario.closing, claim_for.get(id(scenario.closing))),
        ]
        middle = [
            _beat(
                "reveal" if index == 0 else "process",
                None,
                step,
                claim_for.get(id(step)),
            )
            for index, step in enumerate((scenario.reveal, *scenario.steps))
        ]

        def total(body: list[dict[str, Any]]) -> int:
            return visible_length(" ".join(b["text"] for b in head + body + tail))

        # Trim from the end rather than pad with filler: a beat with no shot
        # behind it would fail the contract it is supposed to demonstrate.
        while total(middle) > max_chars and len(middle) > 2:
            middle.pop()

        ordered = head + middle + tail
        for index, beat in enumerate(ordered, start=1):
            beat["id"] = f"B{index:02d}"

        narration = " ".join(beat["text"] for beat in ordered)
        estimated = round(visible_length(narration) / chars_per_sec, 2)
        return {
            "title": f"{MOCK_MARKER} {scenario.resolved_question[:38]}",
            "hook": hook,
            "narration": narration,
            "beats": ordered,
            "target_duration_sec": min(max(estimated, 45.0), 70.0),
            "resolved_question": field(prompt, "RESOLVED_QUESTION", scenario.resolved_question),
            "referenced_claim_ids": [cid for beat in ordered for cid in beat["claim_ids"]],
            "estimated_word_count": len(narration.split()),
        }

    def _scene_plan(self, prompt: str) -> dict[str, Any]:
        topic = field(prompt, "TOPIC", "unknown topic")
        subject = subject_of(topic)
        scenario = scenario_for(topic, subject)
        default_reality = field(prompt, "DEFAULT_REALITY_TYPE", "reconstructed")
        target_duration = float_field(prompt, "TARGET_DURATION_SEC", 58.0)
        min_scene = float_field(prompt, "MIN_SCENE_DURATION_SEC", 1.5)
        max_scene = float_field(prompt, "MAX_SCENE_DURATION_SEC", 9.0)
        max_high = int_field(prompt, "MAX_HIGH_PRIORITY_SCENES", 4)
        script: dict[str, Any] = json_block(prompt, "SCRIPT_JSON", {}) or {}
        beats = script.get("beats") or []
        units: list[dict[str, Any]] = json_block(prompt, "SPEECH_UNITS_JSON", []) or []
        units_by_beat: dict[str, list[str]] = {}
        for unit in units:
            units_by_beat.setdefault(unit.get("beat_id") or "", []).append(unit["id"])

        continuity = [
            {"continuity_id": cid, "fixed_description": description}
            for cid, description in scenario.continuity
        ]
        machine_id = continuity[0]["continuity_id"] if continuity else None

        weights = [float(max(visible_length(beat.get("text", "")), 1)) for beat in beats] or [1.0]
        durations = distribute_durations(
            weights, target_duration, min_each=min_scene, max_each=max_scene
        )

        high_used = 0
        scenes: list[dict[str, Any]] = []
        for index, (beat, duration) in enumerate(zip(beats, durations, strict=True)):
            purpose = beat.get("purpose", "process")
            step = scenario.step_for_spoken(beat.get("text", ""))
            shot = step or _hook_shot(scenario, subject)

            is_high = purpose in {"hook", "surprise"} and high_used < max_high
            if is_high:
                high_used += 1
            is_closing = purpose == "closing"
            priority = "high" if is_high else ("low" if is_closing else "medium")

            scenes.append(
                {
                    "id": f"S{index + 1:02d}",
                    "order": index + 1,
                    "narration": normalize_whitespace(beat.get("text", "")),
                    "caption": shot.caption,
                    # Pull-backs open up the lower third, so move the cue up.
                    "subtitle_position": "top" if "pull back" in shot.camera_path else "bottom",
                    "duration_sec": duration,
                    "purpose": purpose,
                    "question_answered": _question_for(purpose, shot, scenario),
                    "key_object": shot.key_object,
                    "mechanism": shot.mechanism,
                    "visible_change": shot.visible_change,
                    "visual_subject": shot.visual_subject,
                    "environment": scenario.world_environment,
                    "action": shot.action,
                    "camera_path": shot.camera_path,
                    "framing": "vertical 9:16, subject centred in the safe area",
                    "lighting": "soft directional key light with practical accents",
                    "reality_type": "observed" if purpose == "hook" else default_reality,
                    "priority": priority,
                    "asset_type": "image_motion" if priority == "low" else "video",
                    "continuity_ids": list(shot.continuity_ids)
                    or ([machine_id] if machine_id else []),
                    "speech_unit_ids": units_by_beat.get(beat.get("id", ""), []),
                    "claim_ids": list(beat.get("claim_ids", [])),
                    "sfx_cue": shot.sfx_cue,
                    "transition_in": "cut" if index == 0 else "match cut",
                    "transition_out": "match cut",
                    "negative_constraints": list(_SCENE_NEGATIVES),
                }
            )

        return {
            "world": {
                "machine_id": scenario.world_machine_id,
                "visual_style": scenario.world_visual_style,
                "environment": scenario.world_environment,
                "notes": "one continuous journey through a single machine",
            },
            "scenes": scenes,
            "continuity": continuity,
            "visual_notes": f"{MOCK_MARKER} scene plan generated by MockLLMProvider",
        }

    def _fact_check(self, prompt: str) -> dict[str, Any]:
        return {
            "unsupported_sentences": [],
            "overreaching_sentences": [],
            "verdict": "pass",
            "notes": f"{MOCK_MARKER} no review performed",
        }


# -- helpers ---------------------------------------------------------------


#: Korean particles that trail the subject noun in a topic question.
_PARTICLES = ("은", "는", "이", "가", "을", "를", "에서", "에", "의")


def subject_of(topic: str) -> str:
    """The thing the topic is about: the first noun, minus its particle."""
    head = normalize_whitespace(topic).split(" ")[0].strip(" ?!.,")
    for particle in _PARTICLES:
        if head.endswith(particle) and len(head) > len(particle) + 1:
            return head[: -len(particle)]
    return head or "the subject"


def fit_hook(subject: str, max_chars: int) -> str:
    """The shortest question that names the subject and fits the hook budget."""
    candidates = [
        f"{subject} 안에서는 무슨 일이 벌어질까요?",
        f"{subject} 안에서 무슨 일이 생길까요?",
        f"{subject}, 안은 어떻게 생겼을까요?",
        f"{subject}은 어떻게 움직일까요?",
    ]
    for candidate in candidates:
        if visible_length(candidate) <= max_chars:
            return candidate
    # Nothing fits: shorten the subject rather than blow the three-second budget.
    room = max(max_chars - visible_length("은 어떻게 움직일까요?"), 2)
    return f"{subject[:room]}은 어떻게 움직일까요?"


def _sources_from(prompt: str) -> list[dict[str, Any]]:
    sources: list[dict[str, Any]] = json_block(prompt, "SOURCES_JSON", []) or []
    if sources:
        return sources
    return [
        {
            "id": "S01",
            "title": "mock source",
            "url": "https://example.invalid/mock",
            "publisher": "mock",
        }
    ]


def _beat(
    purpose: str, text: str | None, step: Step | None, claim_id: str | None
) -> dict[str, Any]:
    """A beat speaks the scenario's spoken line, not its written claim."""
    spoken = text if text is not None else (step.spoken or step.statement if step else "")
    return {
        "id": "B00",
        "purpose": purpose,
        "text": spoken,
        "claim_ids": [claim_id] if claim_id else [],
        "visualizable": True,
        "visual_payoff": step.visual_payoff if step else "카메라가 대상 앞으로 빠르게 다가간다",
        "emphasis": (step.emphasis or None) if step else None,
    }


def _hook_shot(scenario: Scenario, subject: str) -> Step:
    """The opening exterior shot, built from the world rather than a claim."""
    return Step(
        statement="",
        visual_payoff="카메라가 기계 앞으로 빠르게 다가간다",
        caption=scenario.hook.rstrip("?"),
        key_object=f"{subject} seen from outside",
        mechanism="the camera closes the distance to the machine",
        visible_change="wide view of the room → the machine filling the frame",
        camera_path="fast push-in from across the room toward the machine",
        visual_subject=f"{subject} standing in its everyday location",
        action="the camera approaches until the machine fills the frame",
        continuity_ids=(scenario.continuity[0][0],) if scenario.continuity else (),
    )


def _question_for(purpose: str, shot: Step, scenario: Scenario) -> str:
    if purpose == "hook":
        return scenario.resolved_question
    return f"What happens to {shot.key_object}?"
