"""Deterministic search stand-in.

URLs use the reserved ``.invalid`` TLD so mock sources can never be mistaken
for real citations.
"""

from __future__ import annotations

from ...utils import sha256_text
from ..base import SearchHit

_PUBLISHERS = (
    "Mock Public Agency",
    "Mock Standards Body",
    "Mock Engineering Review",
    "Mock Operator Handbook",
)


class MockSearchProvider:
    name = "mock"

    def __init__(self, results_per_query: int = 4) -> None:
        self.results_per_query = results_per_query

    async def search(self, query: str, *, max_results: int) -> list[SearchHit]:
        count = min(max_results, self.results_per_query)
        digest = sha256_text(query)
        return [
            SearchHit(
                title=f"[MOCK] {query} — reference {index + 1}",
                url=f"https://example.invalid/{digest[:12]}/{index + 1}",
                snippet=(
                    f"Placeholder search result {index + 1} for '{query}'. "
                    "Generated by MockSearchProvider; not a real source."
                ),
                publisher=_PUBLISHERS[index % len(_PUBLISHERS)],
                published_at="2024-01-01",
            )
            for index in range(count)
        ]
