"""Still images from Imagen, over the Gemini API.

    POST models/{model}:predict  ->  predictions[].bytesBase64Encoded

Stills are the fallback for a scene whose video generation failed, and the only
implementation was a mock that rendered a solid colour PNG. On a live run that
put a flat rectangle in the middle of an edit, and the production gate refused
``final.mp4`` because of it -- correctly, but with no way forward.

Using the same key as the video provider is the point: a still generated by a
different vendor to the clips around it will not match them, and there is no
prompt wording that fixes that.

**This provider has not been run against the live API.** Model ids move --
``scripts/list_gemini_models.py`` reports what this key can actually see -- and
the response is walked rather than indexed so a shape change degrades to a
clear error.
"""

from __future__ import annotations

import base64
import binascii
from pathlib import Path
from typing import Any

import httpx

from ...errors import ContentBlockedError, ProviderError
from ...utils import ensure_dir, get_logger
from ..base import ImageResult, assert_live_calls_allowed, require_secret

log = get_logger(__name__)

DEFAULT_BASE_URL = "https://generativelanguage.googleapis.com/v1beta"

_BLOCK_KEYS = ("raiFilteredReason", "filteredReason", "blockedReason")
_BLOCK_PHRASES = ("safety", "blocked", "policy", "filtered", "prohibited")

#: Optional tuning fields Imagen revisions disagree about. Same treatment as the
#: video provider: a 400 naming one of these drops it and retries rather than
#: costing another round trip to discover.
DROPPABLE_PARAMETERS = ("personGeneration", "safetySetting", "outputOptions", "sampleImageSize")


class GeminiImageProvider:
    name = "gemini"
    is_mock = False

    def __init__(
        self,
        *,
        model: str,
        base_url: str = DEFAULT_BASE_URL,
        aspect_ratio: str = "9:16",
        person_generation: str | None = None,
        extra_parameters: dict[str, Any] | None = None,
        timeout_sec: float = 120.0,
        client: httpx.AsyncClient | None = None,
    ) -> None:
        self.model = model
        self.base_url = base_url.rstrip("/")
        self.aspect_ratio = aspect_ratio
        self.person_generation = person_generation
        self.extra_parameters = dict(extra_parameters or {})
        self.timeout_sec = timeout_sec
        self._client = client

    async def generate(
        self,
        *,
        prompt: str,
        width: int,
        height: int,
        destination: str | Path,
        negative_prompt: str | None = None,
    ) -> ImageResult:
        assert_live_calls_allowed(self.name)
        target = Path(destination)
        ensure_dir(target.parent)

        parameters: dict[str, Any] = {
            "sampleCount": 1,
            # Imagen takes a ratio, not a pixel size. The requested width and
            # height decide which ratio to ask for; composition rescales.
            "aspectRatio": _closest_ratio(width, height, self.aspect_ratio),
        }
        if negative_prompt:
            parameters["negativePrompt"] = negative_prompt
        if self.person_generation:
            parameters["personGeneration"] = self.person_generation
        parameters.update(self.extra_parameters)

        body = await self._predict_dropping_rejected(prompt, parameters)

        payload = find_image_bytes(body)
        if payload is None:
            if reason := find_block_reason(body):
                raise ContentBlockedError(
                    f"Imagen refused the prompt: {reason}", provider=self.name, reason=reason
                )
            raise ProviderError(f"Imagen returned no image: {str(body)[:300]}", provider=self.name)
        try:
            target.write_bytes(base64.b64decode(payload))
        except (binascii.Error, ValueError) as exc:
            raise ProviderError(
                f"Imagen returned image bytes that are not valid base64: {exc}",
                provider=self.name,
            ) from exc
        return ImageResult(path=str(target), model=self.model)

    async def _predict_dropping_rejected(
        self, prompt: str, parameters: dict[str, Any]
    ) -> dict[str, Any]:
        """POST, retrying without any tuning field the model rejects.

        The video provider learned this the expensive way: preview models
        disagree about which optional parameters exist, and each rejection
        otherwise costs a round trip to discover. A 400 names the field.
        """
        attempted = dict(parameters)
        dropped: list[str] = []
        while True:
            try:
                return await self._request(
                    f"{self.base_url}/models/{self.model}:predict",
                    {"instances": [{"prompt": prompt}], "parameters": attempted},
                )
            except ContentBlockedError:
                raise
            except ProviderError as exc:
                field = _rejected_parameter(str(exc), attempted)
                if field is None:
                    raise
                attempted.pop(field)
                dropped.append(field)
                log.warning(
                    "imagen_parameter_dropped",
                    parameter=field,
                    model=self.model,
                    dropped_so_far=dropped,
                )

    async def _request(self, url: str, payload: dict[str, Any]) -> dict[str, Any]:
        api_key = require_secret("IMAGE_API_KEY", self.name)
        client = self._client or httpx.AsyncClient(timeout=self.timeout_sec)
        owns = self._client is None
        try:
            response = await client.post(url, headers={"x-goog-api-key": api_key}, json=payload)
        except httpx.TimeoutException as exc:
            raise ProviderError(
                f"Imagen request timed out after {self.timeout_sec}s",
                provider=self.name,
                retryable=True,
            ) from exc
        except httpx.HTTPError as exc:
            raise ProviderError(
                f"Imagen transport error: {exc}", provider=self.name, retryable=True
            ) from exc
        finally:
            if owns:
                await client.aclose()

        if response.status_code >= 400:
            text = response.text[:500]
            if response.status_code in (400, 403) and any(
                phrase in text.lower() for phrase in _BLOCK_PHRASES
            ):
                raise ContentBlockedError(
                    f"Imagen refused the prompt: {text}", provider=self.name, reason=text
                )
            raise ProviderError(
                f"Imagen HTTP {response.status_code}: {text}",
                provider=self.name,
                retryable=response.status_code == 429 or response.status_code >= 500,
            )
        try:
            return dict(response.json())
        except ValueError as exc:
            raise ProviderError(
                f"Imagen returned non-JSON: {response.text[:300]}", provider=self.name
            ) from exc


def _closest_ratio(width: int, height: int, default: str) -> str:
    """The Imagen aspect ratio nearest the requested pixel size."""
    if not width or not height:
        return default
    wanted = width / height
    options = {"1:1": 1.0, "3:4": 0.75, "4:3": 4 / 3, "9:16": 0.5625, "16:9": 16 / 9}
    return min(options, key=lambda name: abs(options[name] - wanted))


def _rejected_parameter(message: str, sent: dict[str, Any]) -> str | None:
    if "400" not in message and "INVALID_ARGUMENT" not in message:
        return None
    lowered = message.lower()
    for field in DROPPABLE_PARAMETERS:
        if field in sent and field.lower() in lowered:
            return field
    return None


def find_image_bytes(node: Any) -> str | None:
    """First base64 image payload in the response, wherever it sits."""
    if isinstance(node, dict):
        for key in ("bytesBase64Encoded", "imageBytes", "b64_json"):
            value = node.get(key)
            if isinstance(value, str) and value:
                return value
        for value in node.values():
            if (found := find_image_bytes(value)) is not None:
                return found
    elif isinstance(node, list):
        for item in node:
            if (found := find_image_bytes(item)) is not None:
                return found
    return None


def find_block_reason(node: Any) -> str | None:
    """A refusal reason, so a policy block is not reported as a broken response."""
    if isinstance(node, dict):
        for key in _BLOCK_KEYS:
            value = node.get(key)
            if value:
                return str(value)
        for value in node.values():
            if (found := find_block_reason(value)) is not None:
                return found
    elif isinstance(node, list):
        for item in node:
            if (found := find_block_reason(item)) is not None:
                return found
    return None
